### ISSUE TITLE
Elaphe666

### ISSUE THREAD

**Issue by Elaphe666** [hbtlabs/chromium#3]
Hi. I've installed this version of Chromium because I was really tired of the horrible white flash when opening and switching pages and tabs. This version works like a charm. After a while using it, I have only found two issues and I wonder if they can be fixed:

The first one doesn't worry me too much: the configuration and extension pages have a black background and many text cannot be read and many times you have to select everything to see what you are doing.

The second one is that the zoom level is not saved or remembered per page, as it happens with Chrome. I don't know if this is an issue with this build or it's a feature in all Chromium versions. I would really like it to remember (everytime I visit a webpage) the zoom I've selected prevously for it.

Thank you.

**Comment by hbt** [comment]
@Elaphe666 this fork version is more recent

https://github.com/imatimba/darker-chromium

can you confirm, you have the same zoom issue?

**Comment by Elaphe666** [comment]
Hi, I have downloaded the version you linked. However, the one I had was 57 and the one I've downloaded now is 56. Fortunatelly, this version is not broken and the zoom levels are remembered. It also has a kind of dark grey background instead of completelly black, which makes the configuration and extension pages readable. Thank you.
